FIND_PACKAGE(PythonInterp)

FUNCTION(CPPLINT TARGET_NAME SOURCES_LIST PROJECT)
	list(SORT SOURCES_LIST)
	list(REMOVE_DUPLICATES SOURCES_LIST)

	ADD_CUSTOM_TARGET(${TARGET_NAME}
		COMMAND "${CMAKE_COMMAND}" -E chdir
			"${CMAKE_SOURCE_DIR}"
			"${PYTHON_EXECUTABLE}"
			"${CMAKE_MODULE_PATH}/cpplint.py"
			"--root=contrib"
			${SOURCES_LIST}
		DEPENDS ${SOURCES_LIST}
		VERBATIM
	)
ENDFUNCTION(CPPLINT)