# Gtest source archive to use
SET(GTEST_ARCHIVE gtest-1.7.0.zip)
# Where to download archive (if it doesn't exist)
SET(GTEST_DLSERVER http://googletest.googlecode.com/files)
SET(GTEST_ROOT ${CMAKE_CURRENT_BINARY_DIR}/gtest-1.7.0)

INCLUDE(FindProtobuf)
FIND_PACKAGE(Protobuf REQUIRED)
FIND_PACKAGE(Threads)

PROTOBUF_GENERATE_CPP(PHP_OPTIONS_SRCS PHP_OPTIONS_HDRS "php_options.proto")
INCLUDE_DIRECTORIES(
	${PROTOBUF_INCLUDE_DIR}
	${CMAKE_CURRENT_BINARY_DIR}
)

IF(NOT EXISTS ${CMAKE_CURRENT_BINARY_DIR}/${GTEST_ARCHIVE})
	MESSAGE("Downloading file: ${CMAKE_SOURCE_DIR}/${GTEST_ARCHIVE}")
	FILE(DOWNLOAD ${GTEST_DLSERVER}/${GTEST_ARCHIVE}
		${CMAKE_CURRENT_BINARY_DIR}/${GTEST_ARCHIVE})

	EXECUTE_PROCESS(COMMAND cmake -E tar zxf ${GTEST_ARCHIVE}
		WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR})

	ADD_SUBDIRECTORY(${CMAKE_CURRENT_BINARY_DIR}/gtest-1.7.0 gtest-1.7.0)
	INCLUDE_DIRECTORIES(${CMAKE_CURRENT_BINARY_DIR}/include ${CMAKE_CURRENT_BINARY_DIR})
ENDIF(NOT EXISTS ${CMAKE_CURRENT_BINARY_DIR}/${GTEST_ARCHIVE})
