<?php
// @@protoc_insertion_point(namespace:.AllTypes)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: AllTypes.proto
 *
 * -*- magic methods -*-
 *
 * @method string getDoubleValue()
 * @method void setDoubleValue(string $value)
 * @method string getFloatValue()
 * @method void setFloatValue(string $value)
 * @method string getInt32Value()
 * @method void setInt32Value(string $value)
 * @method string getInt64Value()
 * @method void setInt64Value(string $value)
 * @method string getUint32Value()
 * @method void setUint32Value(string $value)
 * @method string getUint64Value()
 * @method void setUint64Value(string $value)
 * @method string getSint32Value()
 * @method void setSint32Value(string $value)
 * @method string getSint64Value()
 * @method void setSint64Value(string $value)
 * @method string getFixed32Value()
 * @method void setFixed32Value(string $value)
 * @method string getFixed64Value()
 * @method void setFixed64Value(string $value)
 * @method string getSfixed32Value()
 * @method void setSfixed32Value(string $value)
 * @method string getSfixed64Value()
 * @method void setSfixed64Value(string $value)
 * @method bool getBoolValue()
 * @method void setBoolValue(bool $value)
 * @method string getStringValue()
 * @method void setStringValue(string $value)
 * @method string getBytesValue()
 * @method void setBytesValue(string $value)
 * @method AllTypes getMessageValue()
 * @method void setMessageValue(AllTypes $value)
 * @method array getRDoubleValue()
 * @method void appendRDoubleValue(string $value)
 * @method array getRFloatValue()
 * @method void appendRFloatValue(string $value)
 * @method array getRInt32Value()
 * @method void appendRInt32Value(string $value)
 * @method array getRInt64Value()
 * @method void appendRInt64Value(string $value)
 * @method array getRUint32Value()
 * @method void appendRUint32Value(string $value)
 * @method array getRUint64Value()
 * @method void appendRUint64Value(string $value)
 * @method array getRSint32Value()
 * @method void appendRSint32Value(string $value)
 * @method array getRSint64Value()
 * @method void appendRSint64Value(string $value)
 * @method array getRFixed32Value()
 * @method void appendRFixed32Value(string $value)
 * @method array getRFixed64Value()
 * @method void appendRFixed64Value(string $value)
 * @method array getRSfixed32Value()
 * @method void appendRSfixed32Value(string $value)
 * @method array getRSfixed64Value()
 * @method void appendRSfixed64Value(string $value)
 * @method array getRBoolValue()
 * @method void appendRBoolValue(bool $value)
 * @method array getRStringValue()
 * @method void appendRStringValue(string $value)
 * @method array getRBytesValue()
 * @method void appendRBytesValue(string $value)
 * @method array getRMessageValue()
 * @method void appendRMessageValue(AllTypes $value)
 */
class AllTypes extends ProtocolBuffersMessage
{
    // @@protoc_insertion_point(traits:.AllTypes)

    /**
     * @var string $double_value
     * @tag 1
     * @label optional
     * @type ProtocolBuffers::TYPE_DOUBLE
     **/
    protected $double_value;

    /**
     * @var string $float_value
     * @tag 2
     * @label optional
     * @type ProtocolBuffers::TYPE_FLOAT
     **/
    protected $float_value;

    /**
     * @var string $int32_value
     * @tag 3
     * @label optional
     * @type ProtocolBuffers::TYPE_INT32
     **/
    protected $int32_value;

    /**
     * @var string $int64_value
     * @tag 4
     * @label optional
     * @type ProtocolBuffers::TYPE_INT64
     **/
    protected $int64_value;

    /**
     * @var string $uint32_value
     * @tag 5
     * @label optional
     * @type ProtocolBuffers::TYPE_UINT32
     **/
    protected $uint32_value;

    /**
     * @var string $uint64_value
     * @tag 6
     * @label optional
     * @type ProtocolBuffers::TYPE_UINT64
     **/
    protected $uint64_value;

    /**
     * @var string $sint32_value
     * @tag 7
     * @label optional
     * @type ProtocolBuffers::TYPE_SINT32
     **/
    protected $sint32_value;

    /**
     * @var string $sint64_value
     * @tag 8
     * @label optional
     * @type ProtocolBuffers::TYPE_SINT64
     **/
    protected $sint64_value;

    /**
     * @var string $fixed32_value
     * @tag 9
     * @label optional
     * @type ProtocolBuffers::TYPE_FIXED32
     **/
    protected $fixed32_value;

    /**
     * @var string $fixed64_value
     * @tag 10
     * @label optional
     * @type ProtocolBuffers::TYPE_FIXED64
     **/
    protected $fixed64_value;

    /**
     * @var string $sfixed32_value
     * @tag 11
     * @label optional
     * @type ProtocolBuffers::TYPE_SFIXED32
     **/
    protected $sfixed32_value;

    /**
     * @var string $sfixed64_value
     * @tag 12
     * @label optional
     * @type ProtocolBuffers::TYPE_SFIXED64
     **/
    protected $sfixed64_value;

    /**
     * @var bool $bool_value
     * @tag 13
     * @label optional
     * @type ProtocolBuffers::TYPE_BOOL
     **/
    protected $bool_value;

    /**
     * @var string $string_value
     * @tag 14
     * @label optional
     * @type ProtocolBuffers::TYPE_STRING
     **/
    protected $string_value;

    /**
     * @var string $bytes_value
     * @tag 15
     * @label optional
     * @type ProtocolBuffers::TYPE_BYTES
     **/
    protected $bytes_value;

    /**
     * @var AllTypes $message_value
     * @tag 16
     * @label optional
     * @type ProtocolBuffers::TYPE_MESSAGE
     **/
    protected $message_value;

    /**
     * @var array $r_double_value
     * @tag 21
     * @label optional
     * @type ProtocolBuffers::TYPE_DOUBLE
     **/
    protected $r_double_value;

    /**
     * @var array $r_float_value
     * @tag 22
     * @label optional
     * @type ProtocolBuffers::TYPE_FLOAT
     **/
    protected $r_float_value;

    /**
     * @var array $r_int32_value
     * @tag 23
     * @label optional
     * @type ProtocolBuffers::TYPE_INT32
     **/
    protected $r_int32_value;

    /**
     * @var array $r_int64_value
     * @tag 24
     * @label optional
     * @type ProtocolBuffers::TYPE_INT64
     **/
    protected $r_int64_value;

    /**
     * @var array $r_uint32_value
     * @tag 25
     * @label optional
     * @type ProtocolBuffers::TYPE_UINT32
     **/
    protected $r_uint32_value;

    /**
     * @var array $r_uint64_value
     * @tag 26
     * @label optional
     * @type ProtocolBuffers::TYPE_UINT64
     **/
    protected $r_uint64_value;

    /**
     * @var array $r_sint32_value
     * @tag 27
     * @label optional
     * @type ProtocolBuffers::TYPE_SINT32
     **/
    protected $r_sint32_value;

    /**
     * @var array $r_sint64_value
     * @tag 28
     * @label optional
     * @type ProtocolBuffers::TYPE_SINT64
     **/
    protected $r_sint64_value;

    /**
     * @var array $r_fixed32_value
     * @tag 29
     * @label optional
     * @type ProtocolBuffers::TYPE_FIXED32
     **/
    protected $r_fixed32_value;

    /**
     * @var array $r_fixed64_value
     * @tag 30
     * @label optional
     * @type ProtocolBuffers::TYPE_FIXED64
     **/
    protected $r_fixed64_value;

    /**
     * @var array $r_sfixed32_value
     * @tag 31
     * @label optional
     * @type ProtocolBuffers::TYPE_SFIXED32
     **/
    protected $r_sfixed32_value;

    /**
     * @var array $r_sfixed64_value
     * @tag 32
     * @label optional
     * @type ProtocolBuffers::TYPE_SFIXED64
     **/
    protected $r_sfixed64_value;

    /**
     * @var array $r_bool_value
     * @tag 33
     * @label optional
     * @type ProtocolBuffers::TYPE_BOOL
     **/
    protected $r_bool_value;

    /**
     * @var array $r_string_value
     * @tag 34
     * @label optional
     * @type ProtocolBuffers::TYPE_STRING
     **/
    protected $r_string_value;

    /**
     * @var array $r_bytes_value
     * @tag 35
     * @label optional
     * @type ProtocolBuffers::TYPE_BYTES
     **/
    protected $r_bytes_value;

    /**
     * @var array $r_message_value
     * @tag 36
     * @label optional
     * @type ProtocolBuffers::TYPE_MESSAGE
     * @see AllTypes
     **/
    protected $r_message_value;


    // @@protoc_insertion_point(properties_scope:.AllTypes)

    // @@protoc_insertion_point(class_scope:.AllTypes)

    /**
     * get descriptor for protocol buffers
     *
     * @return ProtocolBuffersDescriptor
     */
    public static function getDescriptor()
    {
        static $descriptor;

        if (!isset($descriptor)) {
            $desc = new ProtocolBuffersDescriptorBuilder();
            $desc->addField(1, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_DOUBLE,
                "name"     => "double_value",
                "required" => false,
                "optional" => true,
                "repeated" => false,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(2, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_FLOAT,
                "name"     => "float_value",
                "required" => false,
                "optional" => true,
                "repeated" => false,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(3, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_INT32,
                "name"     => "int32_value",
                "required" => false,
                "optional" => true,
                "repeated" => false,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(4, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_INT64,
                "name"     => "int64_value",
                "required" => false,
                "optional" => true,
                "repeated" => false,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(5, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_UINT32,
                "name"     => "uint32_value",
                "required" => false,
                "optional" => true,
                "repeated" => false,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(6, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_UINT64,
                "name"     => "uint64_value",
                "required" => false,
                "optional" => true,
                "repeated" => false,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(7, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_SINT32,
                "name"     => "sint32_value",
                "required" => false,
                "optional" => true,
                "repeated" => false,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(8, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_SINT64,
                "name"     => "sint64_value",
                "required" => false,
                "optional" => true,
                "repeated" => false,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(9, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_FIXED32,
                "name"     => "fixed32_value",
                "required" => false,
                "optional" => true,
                "repeated" => false,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(10, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_FIXED64,
                "name"     => "fixed64_value",
                "required" => false,
                "optional" => true,
                "repeated" => false,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(11, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_SFIXED32,
                "name"     => "sfixed32_value",
                "required" => false,
                "optional" => true,
                "repeated" => false,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(12, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_SFIXED64,
                "name"     => "sfixed64_value",
                "required" => false,
                "optional" => true,
                "repeated" => false,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(13, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_BOOL,
                "name"     => "bool_value",
                "required" => false,
                "optional" => true,
                "repeated" => false,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(14, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_STRING,
                "name"     => "string_value",
                "required" => false,
                "optional" => true,
                "repeated" => false,
                "packable" => false,
                "default"  => "",
            )));
            $desc->addField(15, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_BYTES,
                "name"     => "bytes_value",
                "required" => false,
                "optional" => true,
                "repeated" => false,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(16, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_MESSAGE,
                "name"     => "message_value",
                "required" => false,
                "optional" => true,
                "repeated" => false,
                "packable" => false,
                "default"  => null,
                "message" => 'AllTypes',
            )));
            $desc->addField(21, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_DOUBLE,
                "name"     => "r_double_value",
                "required" => false,
                "optional" => false,
                "repeated" => true,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(22, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_FLOAT,
                "name"     => "r_float_value",
                "required" => false,
                "optional" => false,
                "repeated" => true,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(23, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_INT32,
                "name"     => "r_int32_value",
                "required" => false,
                "optional" => false,
                "repeated" => true,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(24, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_INT64,
                "name"     => "r_int64_value",
                "required" => false,
                "optional" => false,
                "repeated" => true,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(25, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_UINT32,
                "name"     => "r_uint32_value",
                "required" => false,
                "optional" => false,
                "repeated" => true,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(26, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_UINT64,
                "name"     => "r_uint64_value",
                "required" => false,
                "optional" => false,
                "repeated" => true,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(27, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_SINT32,
                "name"     => "r_sint32_value",
                "required" => false,
                "optional" => false,
                "repeated" => true,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(28, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_SINT64,
                "name"     => "r_sint64_value",
                "required" => false,
                "optional" => false,
                "repeated" => true,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(29, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_FIXED32,
                "name"     => "r_fixed32_value",
                "required" => false,
                "optional" => false,
                "repeated" => true,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(30, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_FIXED64,
                "name"     => "r_fixed64_value",
                "required" => false,
                "optional" => false,
                "repeated" => true,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(31, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_SFIXED32,
                "name"     => "r_sfixed32_value",
                "required" => false,
                "optional" => false,
                "repeated" => true,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(32, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_SFIXED64,
                "name"     => "r_sfixed64_value",
                "required" => false,
                "optional" => false,
                "repeated" => true,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(33, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_BOOL,
                "name"     => "r_bool_value",
                "required" => false,
                "optional" => false,
                "repeated" => true,
                "packable" => false,
                "default"  => false,
            )));
            $desc->addField(34, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_STRING,
                "name"     => "r_string_value",
                "required" => false,
                "optional" => false,
                "repeated" => true,
                "packable" => false,
                "default"  => "",
            )));
            $desc->addField(35, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_BYTES,
                "name"     => "r_bytes_value",
                "required" => false,
                "optional" => false,
                "repeated" => true,
                "packable" => false,
                "default"  => null,
            )));
            $desc->addField(36, new ProtocolBuffersFieldDescriptor(array(
                "type"     => ProtocolBuffers::TYPE_MESSAGE,
                "name"     => "r_message_value",
                "required" => false,
                "optional" => false,
                "repeated" => true,
                "packable" => false,
                "default"  => null,
                "message" => 'AllTypes',
            )));
            // @@protoc_insertion_point(builder_scope:.AllTypes)

            $descriptor = $desc->build();
        }
        return $descriptor;
    }
}
